
version: '3.7'

services:
  group-buy-api:
    container_name: group_buy_backend
    build: ./
    command: npm start
    working_dir: /usr/src/group-buy-api
    environment:
      POSTGRES_URI: postgres://anita:1qaz@WSX@postgres:5432/group-buy-docker
      REDIS_URI: redis://redis:6379
      JWT: Anitaaaaaa
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/group-buy-api
    links:
      - postgres
      - redis

  postgres:
    environment:
      POSTGRES_PASSWORD: 1qaz@WSX
      POSTGRES_USER: anita
      POSTGRES_DB: group-buy-docker
      POSTGRES_HOST: postgres
    ports:
      - 5432:5432
    build: ./postgres
  redis:
    image: redis
    ports:
      - "6379:6379"




      


